language: ruby
rvm:
- 2.1.2
env:
  matrix:
  - DB=postgresql
  global:
  - secure: qLfw5tgQh/KvNADMHmBGW3/XT1Gfp4XeF3MJfd47pBtHAw+52nlJQ5kka6/Gtz+VO5QjRaQjp9bqFJYc2Cyy5AOfaJ0H+iiFw6GjgSuEDkn1SABOCEoIxZP7Z4iCzimHBFIdDOQpUmSPQEM6iG7zdPAQInO+jLE5uim3joCt7dhHSC94fyHGxUN5bIPZuFfnuIiZtmaYod35hg+HfSxwxLPPBOTrI29UkIA0Qfp5MfJVOpvxBsvV/KNJbAweawcHDddT08BKJ+C3qLX82kez04hIwMBwGsuEu7kJE/nCJf84v2CNFiHFrzkXT9VfqDWmxgd0wG3GjbG4ibajy+TogCPwaHvJcqUlVBzCo+VS0lHoTnPjNZHKsNb4JusyqYcUBcb/2K1Sh26RV6G6rT5lFUcw5hf0E6rdyqKE89QSuk8hH5fbHi/5KFcM7vlCjGk+cVb8hihV8Yg0TBpUO6v/GaHitI7K8fEmN8f1JsS8qzyJI2jEasYFvPt73LycXe2UV1/CTAppSjt7AgosJnJtbZYx+BdAjf8BFRAseVemzb09ifIa/epvqNPo+hefAMQ9ADxmyGrLG7FesH9T0ysVD6D15k5c8gwdOTIyXFto9dzJ9WlTdES6NckQZQqvlnWcdTl5fys4yPlEJcb3YzrT7OZVrMf7T3HoSyL/9I+uDXo=
  - secure: bNjBPkxciOeYwfu8wOAwnS6+iqeNXVP3u7QP6FJv39ktW5N1dXsbL5Kdh3jLesdLLcB6lQwy8vb4CNDYF1DqlbqERYim2ALzIRUp0yTcScmGENmIIA2Fxq4/W6g37jyNeAv6dZvsRByuVooDl+ic+bHZqfpIww4jZrTaXnP94u1TpXmy8z4Rzm8e4q3l4W7fQuYxTl9Qc5uaPL0l+fN8o9PiBrHsYffEni+lpwFug6u/M8c1m0KS9gauAp3yjkYSUNZS8YDzTAjX03w8gonyBiZ31TFyXmoYEefH9nHOwI52+r7TXA+NGKghhnRXMI2YSnrFHdYr54cXmkf2NQNMj3c9dMKg7X3n91inaDjqXWp39QPG+aEj7XSSp/arnerrcSpGR18FKVqUJGASUDqTINRziAiBhPvnT2YOp0dcw6wfdeA2HwqifUsRRusI9qNiYgEQVyzLoLab2FpQzi8TV3WNODqbzbCOw/WuQGwWbskp3eer6EfMqYixDGH74Q24ilpV2XxdaxiGpQTgx923hvz06AEG8L+pU0hsdLWOSb9FPI/m/mcEmqM2gTbtwr5ipKqlgoDhuuJm5hfV4nXnagUq000uehzBXsWLrgOWg7gXDVesKP6T3zs/J4XxW4TGLASYcUuNwhiSI/QwyKkTvSyu9HYWC0UWTAIRpPch9h0=
script:
- bundle exec rake spec
before_script:
- bundle exec rake db:create RAILS_ENV=test
- bundle exec rake db:migrate
- bundle exec rake db:test:prepare
