production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_geolocation_key: <%= ENV["GOOGLE_GEOLOCATION_KEY"] %>
  dark_sky_key: <%= ENV["DARK_SKY_KEY"] %>
  twilio_account_sid: <%= ENV["TWILIO_ACCOUNT_SID"] %>
  twilio_auth_token: <%= ENV["TWILIO_AUTH_TOKEN"] %>
